# Generated by Django 2.0.2 on 2018-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=50)),
                ('labels', models.CharField(max_length=250)),
                ('confidence', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
