# Generated by Django 2.0.2 on 2018-03-28 18:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadImages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
